"""Validate a build dict against the SETS build-JSON contract.

WARP writes build files that SETS reads. SETS is forgiving in the worst
possible way: `remove_invalid_build_items` silently drops anything it
cannot resolve, and `load_boff_stations` renders a `None` seat spec as
the literal string "None". Both look like recognition failures to a
user. This module catches those before the file is written.

The container shape (which keys exist, how long every list is) comes
from `warp/data/sets_contract.json`, generated by `tools/sets_contract.py`
from a real SETS release. Value rules are hand-written here because they
live in SETS' *reading* code, not in its skeleton — `empty_build()` itself
carries `boff_specs[5] == ['Tactical', None]`, which `load_boff_stations`
would render as "Tactical / None". The contract's `consumers` hashes
exist to tell us when those functions change upstream.

Severity:
  * `error`   — SETS will lose or mangle data (dropped item, "None / None"
                seat label, station missing from the markdown export).
  * `warning` — loads fine, but something is off (ability recorded at a
                rank its cargo entry doesn't offer at that slot).

Deliberately dependency-free: no `warp.debug`, no cargo import at module
level, so `tools/` and tests can import it cheaply. Logging is the
caller's job (see `warp.sets_export`).
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from urllib.parse import urlencode

CONTRACT_PATH = Path(__file__).resolve().parent / 'data' / 'sets_contract.json'

ISSUE_BASE_URL = 'https://github.com/raman78/sto-warp/issues/new'
# GitHub rejects issue URLs beyond roughly 8 kB; stay well under it.
_MAX_URL_LEN = 6000
_MAX_ISSUE_ROWS = 15

# `src.constants.RARITY_COLORS` — SETS turns these into overlay attribute
# names (`rarity.lower().replace(' ', '')`), so an unknown value raises.
RARITIES = frozenset({'Common', 'Uncommon', 'Rare', 'Very Rare', 'Ultra Rare', 'Epic'})
BOFF_RANKS = ('I', 'II', 'III')
PROFESSIONS = frozenset({'Tactical', 'Engineering', 'Science'})

# Seat rank a BOFF ability tier unlocks at (cargo field `rank<N>rank`)
# → BOFF slot index. The wiki spells Lieutenant Commander three ways;
# SETS' own `constants.BOFF_RANKS` knows two of them, so an ability
# using the third gets an empty tooltip there — it still renders.
# Ground abilities carry kit-module wikitext in these fields instead of
# a rank, which is why lookups must be allowed to miss.
SEAT_RANK_SLOT = {
    'Ensign': 0,
    'Lieutenant': 1,
    'Lt. Commander': 2,
    'Lieutenant Commander': 2,
    'Lt Commander': 2,
    'Commander': 3,
}

# Categories SETS loads through `load_equipment_cat` → `slot_equipment_item`,
# which reads item['rarity'] / ['mark'] / ['modifiers'] and looks the name up
# in `cache.equipment[<category>]`. Category names double as cargo buckets.
EQUIPMENT_KEYS = {
    'space': ('fore_weapons', 'aft_weapons', 'experimental', 'devices', 'hangars',
              'deflector', 'sec_def', 'engines', 'core', 'shield',
              'uni_consoles', 'eng_consoles', 'sci_consoles', 'tac_consoles'),
    'ground': ('kit_modules', 'weapons', 'ground_devices', 'kit', 'armor',
               'ev_suit', 'personal_shield'),
}

# Categories SETS loads through `load_trait_cat` → `slot_trait_item`, which
# needs only `item` but looks the name up in an environment- and
# category-specific cargo bucket. Value = bucket in `cargo.traits()`;
# `starship_traits` has its own flat cache and is handled separately.
TRAIT_KEYS = {
    'space': {'traits': 'personal', 'rep_traits': 'rep', 'active_rep_traits': 'active_rep'},
    'ground': {'traits': 'personal', 'rep_traits': 'rep', 'active_rep_traits': 'active_rep'},
}

_SKILL_TREES = ('eng', 'sci', 'tac')


@dataclass(frozen=True)
class Violation:
    path: str
    rule: str
    expected: str
    got: str
    severity: str = 'error'

    def __str__(self) -> str:
        return f'{self.path} [{self.rule}] expected {self.expected}, got {self.got}'


def shape_of(obj, path: str = '') -> dict[str, str]:
    """Flatten `obj` into `path -> token` for every container it holds.

    Mirrors the generator in `tools/sets_contract.py` (which imports this
    function) so stored contract and runtime check cannot drift apart.
    Scalars are omitted — their default value is not part of the contract.
    """
    if isinstance(obj, dict):
        out = {path: 'dict{' + ','.join(sorted(obj)) + '}'}
        for key, value in obj.items():
            out.update(shape_of(value, f'{path}/{key}'))
        return out
    if isinstance(obj, list):
        out = {path: f'list[{len(obj)}]'}
        for index, value in enumerate(obj):
            out.update(shape_of(value, f'{path}[{index}]'))
        return out
    return {}


@lru_cache(maxsize=1)
def contract() -> dict:
    return json.loads(CONTRACT_PATH.read_text(encoding='utf-8'))


def _describe(value) -> str:
    if isinstance(value, dict):
        return 'dict{' + ','.join(sorted(value)) + '}'
    if isinstance(value, list):
        return f'list[{len(value)}]'
    return repr(value)


# --- individual checks ----------------------------------------------------

def _check_shape(build: dict, out: list[Violation]) -> None:
    """Every container the contract names must be present, same size.

    Only one direction is checked: extra paths are what a *filled* build
    looks like (a slot holding an item dict where the skeleton had `''`).
    Extra dict keys still surface, because the `dict{...}` token carries
    the whole key set.
    """
    actual = shape_of(build)
    for path, token in contract()['shape'].items():
        got = actual.get(path)
        if got is None:
            out.append(Violation(path or '/', 'missing', token, 'absent'))
        elif got != token:
            out.append(Violation(path or '/', 'shape', token, got))


def _check_version(build: dict, out: list[Violation]) -> None:
    expected = contract()['build_version']
    got = build.get('_version')
    if got != expected:
        out.append(Violation('/_version', 'build_version', repr(expected), repr(got)))


def _check_boff_seats(build: dict, out: list[Violation]) -> None:
    """Seat professions/specs must be strings.

    `load_boff_stations` compares `boff_spec[1] == ''` and interpolates
    both entries into the seat label, so `None` renders as "None / None";
    `ExportWindow.get_build_markdown` guards with `if any(specs)` and
    drops the whole station from the markdown export.
    """
    for seat_id, spec in enumerate(build.get('space', {}).get('boff_specs', [])):
        path = f'/space/boff_specs[{seat_id}]'
        if not isinstance(spec, list) or len(spec) != 2:
            out.append(Violation(path, 'seat_spec', 'list[2]', _describe(spec)))
            continue
        profession, specialisation = spec
        # `''` is legal: that is what SETS stores for a seat the ship
        # doesn't have, and `if any(specs)` skips it downstream.
        if not isinstance(profession, str):
            out.append(Violation(f'{path}[0]', 'seat_profession',
                                 "str ('' when the seat is hidden)", repr(profession)))
        elif profession and profession not in PROFESSIONS:
            out.append(Violation(f'{path}[0]', 'seat_profession',
                                 'one of ' + '/'.join(sorted(PROFESSIONS)),
                                 repr(profession), 'warning'))
        if not isinstance(specialisation, str):
            out.append(Violation(f'{path}[1]', 'seat_specialisation',
                                 "str ('' when none)", repr(specialisation)))

    ground = build.get('ground', {})
    for seat_id, profession in enumerate(ground.get('boff_profs', [])):
        if profession not in PROFESSIONS:
            out.append(Violation(f'/ground/boff_profs[{seat_id}]', 'seat_profession',
                                 'one of ' + '/'.join(sorted(PROFESSIONS)), repr(profession)))
    for seat_id, specialisation in enumerate(ground.get('boff_specs', [])):
        if not isinstance(specialisation, str) or specialisation == '':
            out.append(Violation(f'/ground/boff_specs[{seat_id}]', 'seat_specialisation',
                                 'non-empty str', repr(specialisation)))


def _check_equipment(build: dict, cache, out: list[Violation]) -> None:
    for environment, keys in EQUIPMENT_KEYS.items():
        for key in keys:
            for index, item in enumerate(build.get(environment, {}).get(key, [])):
                path = f'/{environment}/{key}[{index}]'
                if item is None or item == '':
                    continue
                if not isinstance(item, dict):
                    out.append(Violation(path, 'slot_type', "None / '' / item dict",
                                         _describe(item)))
                    continue
                missing = {'item', 'rarity', 'mark', 'modifiers'} - set(item)
                if missing:
                    out.append(Violation(path, 'item_keys',
                                         'item,rarity,mark,modifiers',
                                         'missing ' + ','.join(sorted(missing))))
                name = item.get('item')
                if not isinstance(name, str) or name == '':
                    out.append(Violation(path, 'item_name', 'non-empty str', repr(name)))
                    continue
                rarity = item.get('rarity')
                if rarity not in RARITIES:
                    out.append(Violation(path, 'rarity',
                                         'one of ' + '/'.join(sorted(RARITIES)), repr(rarity)))
                modifiers = item.get('modifiers')
                if not isinstance(modifiers, list):
                    out.append(Violation(path, 'modifiers', 'list', _describe(modifiers)))
                elif any(m is not None and not isinstance(m, str) for m in modifiers):
                    out.append(Violation(path, 'modifiers', 'str / None entries',
                                         repr(modifiers)))
                if cache is not None and name not in cache.equipment.get(key, {}):
                    out.append(Violation(path, 'unknown_item',
                                         f'name present in cargo equipment[{key}]', repr(name)))


def _check_traits(build: dict, cache, out: list[Violation]) -> None:
    for environment, keys in TRAIT_KEYS.items():
        for key, bucket in keys.items():
            for index, trait in enumerate(build.get(environment, {}).get(key, [])):
                path = f'/{environment}/{key}[{index}]'
                if trait is None or trait == '':
                    continue
                if not isinstance(trait, dict) or 'item' not in trait:
                    out.append(Violation(path, 'trait_type', "None / '' / {'item': name}",
                                         _describe(trait)))
                    continue
                name = trait['item']
                if cache is not None and name not in cache.traits[environment][bucket]:
                    out.append(Violation(path, 'unknown_trait',
                                         f'name present in cargo traits[{environment}][{bucket}]',
                                         repr(name)))

    for index, trait in enumerate(build.get('space', {}).get('starship_traits', [])):
        path = f'/space/starship_traits[{index}]'
        if trait is None or trait == '':
            continue
        if not isinstance(trait, dict) or 'item' not in trait:
            out.append(Violation(path, 'trait_type', "None / '' / {'item': name}",
                                 _describe(trait)))
            continue
        if cache is not None and trait['item'] not in cache.starship_traits:
            out.append(Violation(path, 'unknown_trait',
                                 'name present in cargo starship_traits', repr(trait['item'])))


def _check_boff_abilities(build: dict, cache, out: list[Violation]) -> None:
    """Abilities need a Roman rank and a name SETS' cache knows.

    `load_boff_stations` does `boff_abilities['all'][item][rank]`, so an
    unknown name raises (and `remove_invalid_build_items` then wipes the
    slot). The slot-vs-rank check is a warning: SETS renders it, but the
    ability is not actually offered at that slot — cargo's `rank<N>rank`
    names the seat rank each Roman tier unlocks at.
    """
    all_abilities = cache.boff_abilities.get('all', {}) if cache is not None else {}

    for environment in ('space', 'ground'):
        for seat_id, seat in enumerate(build.get(environment, {}).get('boffs', [])):
            if not isinstance(seat, list):
                continue
            for slot_index, ability in enumerate(seat):
                path = f'/{environment}/boffs[{seat_id}][{slot_index}]'
                if ability is None or ability == '':
                    continue
                if not isinstance(ability, dict):
                    out.append(Violation(path, 'ability_type', "None / '' / ability dict",
                                         _describe(ability)))
                    continue
                name = ability.get('item')
                rank = ability.get('rank')
                if not isinstance(name, str) or name == '':
                    out.append(Violation(path, 'ability_name', 'non-empty str', repr(name)))
                    continue
                if rank not in BOFF_RANKS:
                    out.append(Violation(path, 'ability_rank',
                                         'one of ' + '/'.join(BOFF_RANKS), repr(rank)))
                    continue
                if name.rpartition(' ')[2] in BOFF_RANKS:
                    out.append(Violation(path, 'ability_name',
                                         'base name without rank suffix', repr(name)))
                if cache is None:
                    continue
                entry = all_abilities.get(name)
                if entry is None:
                    out.append(Violation(path, 'unknown_ability',
                                         'name present in cargo boff_abilities[all]', repr(name)))
                    continue
                unlock = entry.get(f'rank{BOFF_RANKS.index(rank) + 1}rank')
                expected_slot = SEAT_RANK_SLOT.get(unlock)
                if expected_slot is None:
                    # Ground abilities (kit modules) and abilities whose
                    # tier is absent carry no seat rank — no claim to make.
                    continue
                if expected_slot != slot_index:
                    out.append(Violation(path, 'rank_slot',
                                         f'{name} {rank} at slot {expected_slot}',
                                         f'slot {slot_index}', 'warning'))


def _check_captain(build: dict, out: list[Violation]) -> None:
    captain = build.get('captain', {})
    if not isinstance(captain.get('elite'), bool):
        out.append(Violation('/captain/elite', 'field_type', 'bool',
                             repr(captain.get('elite'))))
    for key in ('career', 'faction', 'name', 'primary_spec', 'secondary_spec', 'species'):
        if not isinstance(captain.get(key), str):
            out.append(Violation(f'/captain/{key}', 'field_type', 'str', repr(captain.get(key))))


def _check_skills(build: dict, out: list[Violation]) -> None:
    for tree in _SKILL_TREES:
        nodes = build.get('space_skills', {}).get(tree, [])
        if any(not isinstance(node, bool) for node in nodes):
            out.append(Violation(f'/space_skills/{tree}', 'node_type', 'all bool',
                                 'non-bool entries'))
    for page_index, page in enumerate(build.get('ground_skills', [])):
        if not isinstance(page, list) or any(not isinstance(node, bool) for node in page):
            out.append(Violation(f'/ground_skills[{page_index}]', 'node_type', 'all bool',
                                 _describe(page)))


# --- entry points ---------------------------------------------------------

def validate_sets_build(build: dict, cache=None) -> list[Violation]:
    """Check `build` against the SETS contract; empty list means clean.

    `cache` is an optional `warp.data.cargo.cache_view()`. Without it the
    structural and value rules still run; the name-existence rules (the
    ones that predict SETS' silent item removal) are skipped.
    """
    out: list[Violation] = []
    if not isinstance(build, dict):
        return [Violation('/', 'root_type', 'dict', _describe(build))]
    _check_shape(build, out)
    _check_version(build, out)
    _check_boff_seats(build, out)
    _check_equipment(build, cache, out)
    _check_traits(build, cache, out)
    _check_boff_abilities(build, cache, out)
    _check_captain(build, out)
    _check_skills(build, out)
    return out


def errors(violations: list[Violation]) -> list[Violation]:
    return [v for v in violations if v.severity == 'error']


def summarise(violations: list[Violation], limit: int = 5) -> str:
    """One-line summary for the log / status bar."""
    if not violations:
        return 'clean'
    n_errors = len(errors(violations))
    head = '; '.join(str(v) for v in violations[:limit])
    if len(violations) > limit:
        head += f'; … +{len(violations) - limit} more'
    return f'{len(violations)} violations ({n_errors} errors): {head}'


def issue_url(violations: list[Violation], meta: dict | None = None) -> str:
    """Pre-filled GitHub issue for the maintainer.

    Returns a URL only — opening it shows the user a form they submit
    themselves. The body carries item names and version strings, never
    file paths or user names.
    """
    meta = meta or {}
    lines = [
        'WARP wrote a SETS build that violates the format contract.',
        '',
        '| field | value |',
        '| --- | --- |',
    ]
    lines += [f'| {key} | {value} |' for key, value in meta.items()]
    lines += [
        f'| sets_contract | {contract()["sets_tag"]} |',
        '',
        f'### Violations ({len(violations)}, {len(errors(violations))} errors)',
        '',
        '| path | rule | expected | got | severity |',
        '| --- | --- | --- | --- | --- |',
    ]
    for violation in violations[:_MAX_ISSUE_ROWS]:
        lines.append(f'| `{violation.path}` | {violation.rule} | {violation.expected} | '
                     f'`{violation.got}` | {violation.severity} |')
    if len(violations) > _MAX_ISSUE_ROWS:
        lines.append(f'| … | +{len(violations) - _MAX_ISSUE_ROWS} more | | | |')
    lines += ['', 'Please attach `warp_system.log` — it holds the full list.']

    body = '\n'.join(lines)
    while True:
        query = urlencode({
            'labels': 'sets-schema',
            'title': f'SETS schema: {len(violations)} violations on export',
            'body': body,
        })
        url = f'{ISSUE_BASE_URL}?{query}'
        if len(url) <= _MAX_URL_LEN or '\n' not in body:
            return url
        body = body[:body.rfind('\n')]
