"""Snapshot & drift-check the SETS build-JSON contract.

sto-warp writes build files that SETS loads. Nothing in either codebase
enforces that the two agree, so this script freezes what we rely on into
`warp/data/sets_contract.json` and re-checks it against the newest SETS
release from CI.

Two independent things are captured:

  1. `shape` — the container skeleton of `buildhelpers.empty_build('full')`:
     which keys every section has and how long every list is. Scalars are
     recorded as `scalar`, not as their default's type, because a default
     of `''` says nothing about which values a *loaded* build may carry.

  2. `consumers` — sha256 of the source of the SETS functions whose
     behaviour `warp/sets_schema.py` mirrors by hand. The skeleton alone
     cannot catch every contract: SETS' own skeleton has
     `boff_specs[5] == ['Tactical', None]`, yet `load_boff_stations`
     renders `None` as the literal string "None". When one of these
     functions changes upstream, the mirrored rules need a human look.

Usage:
    python tools/sets_contract.py --refresh [--tag v3.1.1]
    python tools/sets_contract.py --check

`--check` exits 1 on drift and prints a diff; the workflow turns that
into a GitHub issue. Both modes import SETS from the environment
(`pip install STO-SETS==<version>`); this repo never depends on it at
runtime.
"""
from __future__ import annotations

import argparse
import hashlib
import inspect
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# Shape generation lives with the validator so the stored contract and the
# runtime check cannot drift apart.
from warp.sets_schema import CONTRACT_PATH, shape_of  # noqa: E402

# SETS functions whose behaviour warp/sets_schema.py reproduces. Keyed as
# `module:qualname`; the value stored in the contract is a sha256 of the
# function's source, so any edit upstream surfaces as drift.
CONSUMERS = (
    'src.buildhelpers:empty_build',
    'src.buildhelpers:parse_boff_stations',
    'src.buildloader:BuildLoader.load_build_file',
    'src.buildloader:BuildLoader.merge_build',
    'src.buildloader:BuildLoader.update_build_version',
    'src.buildloader:BuildLoader.remove_invalid_build_items',
    'src.buildmanager:BuildManager.load_build',
    'src.buildmanager:BuildManager.load_boff_stations',
    'src.buildmanager:BuildManager.load_equipment_cat',
    'src.buildmanager:BuildManager.load_trait_cat',
    'src.buildmanager:BuildManager.slot_equipment_item',
    'src.buildmanager:BuildManager.slot_trait_item',
    'src.buildmanager:BuildManager.update_boff_seat',
    'src.exportwindow:ExportWindow.get_build_markdown',
    'src.textedit:add_equipment_tooltip_header',
)


def _resolve(dotted: str):
    """Return the named function, or None when upstream no longer has it."""
    module_name, _, qualname = dotted.partition(':')
    module = __import__(module_name, fromlist=['_'])
    target = module
    for part in qualname.split('.'):
        target = getattr(target, part, None)
        if target is None:
            return None
    return target


def _consumer_hashes() -> dict[str, str]:
    """Hash each mirrored function's source.

    A vanished function is recorded as `<missing>` rather than raising —
    that is drift to report, not a broken run. SETS 3.1.0 replaced
    `get_boff_spec` with `parse_boff_stations`, exactly the kind of
    change this contract exists to surface.
    """
    hashes = {}
    for dotted in CONSUMERS:
        target = _resolve(dotted)
        if target is None:
            hashes[dotted] = '<missing>'
            continue
        source = inspect.getsource(target)
        hashes[dotted] = hashlib.sha256(source.encode('utf-8')).hexdigest()
    return hashes


def _sets_version() -> str:
    from importlib.metadata import PackageNotFoundError, version
    try:
        return version('STO-SETS')
    except PackageNotFoundError:
        return 'unknown'


def build_contract(tag: str | None = None) -> dict:
    """Read the installed SETS and return a fresh contract dict."""
    from src.buildhelpers import empty_build
    from src.constants import BUILD_VERSION

    sets_version = _sets_version()
    return {
        '_comment': 'Generated by tools/sets_contract.py — do not hand-edit.',
        'sets_version': sets_version,
        'sets_tag': tag or f'v{sets_version}',
        'build_version': BUILD_VERSION,
        'shape': shape_of(empty_build('full')),
        'consumers': _consumer_hashes(),
    }


def diff_contract(old: dict, new: dict) -> list[str]:
    """Human-readable drift lines; empty list means the contract holds."""
    lines = []

    if old.get('build_version') != new.get('build_version'):
        lines.append(
            f"build_version: {old.get('build_version')} -> {new.get('build_version')}")

    old_shape, new_shape = old.get('shape', {}), new.get('shape', {})
    for path in sorted(set(old_shape) - set(new_shape)):
        lines.append(f'shape removed: {path or "/"} (was {old_shape[path]})')
    for path in sorted(set(new_shape) - set(old_shape)):
        lines.append(f'shape added: {path or "/"} ({new_shape[path]})')
    for path in sorted(set(old_shape) & set(new_shape)):
        if old_shape[path] != new_shape[path]:
            lines.append(f'shape changed: {path or "/"}: {old_shape[path]} -> {new_shape[path]}')

    old_consumers, new_consumers = old.get('consumers', {}), new.get('consumers', {})
    for name in sorted(set(old_consumers) - set(new_consumers)):
        lines.append(f'consumer gone: {name} — mirrored rule may be obsolete')
    for name in sorted(set(new_consumers) - set(old_consumers)):
        lines.append(f'consumer new: {name}')
    for name in sorted(set(old_consumers) & set(new_consumers)):
        if old_consumers[name] != new_consumers[name]:
            lines.append(f'consumer changed: {name} — re-read it against warp/sets_schema.py')

    return lines


def load_contract(path: Path = CONTRACT_PATH) -> dict:
    return json.loads(path.read_text(encoding='utf-8'))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--refresh', action='store_true',
                      help='regenerate warp/data/sets_contract.json from the installed SETS')
    mode.add_argument('--check', action='store_true',
                      help='compare the installed SETS against the stored contract; exit 1 on drift')
    parser.add_argument('--tag', default=None,
                        help='SETS release tag to record (default: v<installed version>)')
    args = parser.parse_args(argv)

    try:
        new = build_contract(args.tag)
    except ImportError as exc:
        print(f'error: SETS not importable ({exc}) — pip install STO-SETS', file=sys.stderr)
        return 2

    if args.refresh:
        CONTRACT_PATH.write_text(
            json.dumps(new, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
        print(f'wrote {CONTRACT_PATH} for SETS {new["sets_tag"]} '
              f'({len(new["shape"])} shape entries, {len(new["consumers"])} consumers)')
        return 0

    old = load_contract()
    lines = diff_contract(old, new)
    if not lines:
        print(f'contract holds: {old["sets_tag"]} -> {new["sets_tag"]} '
              f'({len(new["shape"])} shape entries checked)')
        return 0

    print(f'SETS contract drift: {old["sets_tag"]} -> {new["sets_tag"]}', file=sys.stderr)
    for line in lines:
        print(f'  {line}', file=sys.stderr)
    return 1


if __name__ == '__main__':
    sys.exit(main())
